name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019


    steps:
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v2
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test