name: Run test

on: workflow_dispatch

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

  steps:
    - name: start selenoid
      uses: Xotabu4/selenoid-github-action@v1
    with:
      selenoid-start-arguments: 
        --args "-timeout 60s"

    - uses: actions/checkout@v1
    - name: Switch to Node.js 14.16.0
      uses: actions/setup-node@v1
      with:
          node-version: 14.16.0 

    - name: Run tests
      run: npm cit