  name: Node

on:
  push:
    branches: [ main ]

jobs:
      runs-on: windows-2019
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - run: npm ci
#      - run: npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
      - name: Run tests
        run: npm run test
      - name: Generate allure-report
        if: always()
        run: npm run allure:generate
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report-ta
          path: allure-report