name: Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm run test
    - name: Generate allure-report
      if: always()
      run: npm run allure:generate
    - name: Publishing Allure artifact to Github Actions
      uses: actions/upload-artifact@v2
      if: always()
        with:
          name: allure-report-ta
          path: allure-report   
